'use client';
import { useEffect, useMemo, useState } from 'react';
const configuredAPI=process.env.NEXT_PUBLIC_API_URL||'';
export default function Home(){
 const [events,setEvents]=useState<any[]>([]),[metrics,setMetrics]=useState<any>({}),[dexes,setDexes]=useState<any[]>([]),[filter,setFilter]=useState('all'),[chain,setChain]=useState('solana'),[status,setStatus]=useState('CONNECTING');
 useEffect(()=>{const API=configuredAPI||window.location.origin;const wsurl=API.replace(/^http/,'ws')+'/ws';const ws=new WebSocket(wsurl);ws.onopen=()=>setStatus('LIVE');ws.onclose=()=>setStatus('OFFLINE');ws.onerror=()=>setStatus('ERROR');ws.onmessage=e=>{try{setEvents(v=>[JSON.parse(e.data),...v].slice(0,200))}catch{}};const load=async()=>{try{const [m,d]=await Promise.all([fetch(`${API}/api/metrics`,{cache:'no-store'}),fetch(`${API}/api/dex`,{cache:'no-store'})]);setMetrics(await m.json());setDexes(await d.json())}catch{setStatus('OFFLINE')}};load();const timer=setInterval(load,3000);return()=>{ws.close();clearInterval(timer)}},[]);
 const visible=useMemo(()=>events.filter(e=>(filter==='all'||e.type===filter)&&(chain==='all'||e.chain===chain)),[events,filter,chain]);const source=metrics.sources||{};const dexCounts=metrics.dexEvents||{};
 return <main><div className="ambient-bg" aria-hidden="true"/><header><div className="brand"><b>HANZI / LIQUIDITY INTELLIGENCE</b><span className={status==='LIVE'?'live':''}>● {status}</span></div><nav><button className={chain==='solana'?'active':''} onClick={()=>setChain('solana')}>SOLANA</button><button className={chain==='bnb'?'active':''} onClick={()=>setChain('bnb')}>BNB</button></nav></header>
 <section className="hanziBanner"><div className="bannerCopy"><span className="bannerKicker">HANZI · ON-CHAIN INTELLIGENCE TERMINAL</span><h1>Every price dislocation = opportunity.</h1><p>Real-time Pump.fun, Flap.sh, DEX flow and liquidity intelligence for multi-market monitoring.</p><div className="bannerPills"><span>24/7 MONITORING</span><span>REAL DATA ONLY</span><span>READ-ONLY SCANNER</span></div></div><div className="systemFlow"><b>THE SYSTEM</b><span>Claude Code → Trading Logic</span><span>Real-time API → Pump.fun + Flap.sh</span><span>iPad → Multi-market Monitoring</span><span>Solana → Meme Market Scanner</span><span>Phantom → Wallet Connect</span></div></section>
 <section className="hero"><div><div className="eyebrow">REAL ON-CHAIN DATA / DEX FLOW / SMART MONEY / LIQUIDITY MATRIX</div><h2>{chain.toUpperCase()} Intelligence Terminal</h2><p>Blockchain events only. DEX discovery, pool creation, swaps, launchpad activity and migration are normalized into one live feed.</p></div><div className="sourcebox"><small>DATA SOURCES</small><strong>Solana RPC · BSC WS · PumpPortal</strong><span>No synthetic fallback. Venue availability is shown from live source status.</span></div></section>
 <section className="grid"><Card t="EVENTS" v={events.length} d="real normalized events"/><Card t="SOLANA" v={metrics.solanaEvents||0} d={source.solana||'WAITING'}/><Card t="BNB" v={metrics.bnbEvents||0} d={source.bnb||'WAITING'}/><Card t="PUMPPORTAL" v={metrics.pumpEvents||0} d={source.pumpportal||'WAITING'}/></section>
 <section className="panel"><div className="panelhead"><h2>DEX / LAUNCHPAD TRACKING</h2><span>{dexes.length} configured venues</span></div><div className="dexgrid">{dexes.filter(d=>d.chain===chain).map(d=><div className="dexcard" key={d.id}><b>{d.name}</b><span>{d.kind.toUpperCase()}</span><strong>{dexCounts[d.id]||0}</strong><small>events tracked</small></div>)}</div></section>
 <section className="control"><div><small>DATA POLICY</small><b>REAL DATA ONLY</b><span> No mock / no demo / no synthetic fallback</span></div><div><small>LATENCY</small><b>{metrics.latencyMs||0} ms</b></div><div><small>API MODE</small><b>READ-ONLY SCANNER</b></div></section>
 <section className="toolbar">{['all','token_create','trade','pool_create','migration','liquidity','log','block','chain_status'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x.toUpperCase()}</button>)}</section>
 <section className="matrix"><div className="panel"><div className="panelhead"><h2>LIVE LIQUIDITY MATRIX</h2><span>{visible.length} events</span></div>{visible.length?visible.map((e,i)=><div className="event" key={`${e.txHash||e.ts}-${i}`}><i/><div className="eventmain"><b>{String(e.type||'event').replaceAll('_',' ').toUpperCase()}</b><span>{e.dex||e.symbol||e.token||e.pool||e.txHash||e.source}</span></div><div className="eventmeta"><span>{e.side||e.chain}</span></div></div>):<div className="empty">NO DATA — waiting for real blockchain events.</div>}</div><aside className="panel"><h2>INTELLIGENCE</h2><M n="Data Mode" v="REAL ONLY"/><M n="Solana RPC" v={source.solana||'WAITING'}/><M n="BNB RPC" v={source.bnb||'WAITING'}/><M n="PumpPortal" v={source.pumpportal||'WAITING'}/><M n="PancakeSwap" v={`${(dexCounts['pancakeswap-v2']||0)+(dexCounts['pancakeswap-v3']||0)} events`}/><M n="Flap.sh" v={`${dexCounts.flap||0} events`}/><M n="Pump.fun" v={`${dexCounts['pumpfun-pumpswap']||0} events`}/><M n="Smart Money" v="SCORING"/><M n="Liquidity Matrix" v="11 ENGINES"/><M n="Synthetic Data" v="DISABLED"/></aside></section></main>;
}
function Card(p:any){return <div className="card"><small>{p.t}</small><strong>{p.v}</strong><p>{p.d}</p></div>};function M(p:any){return <div className="metric"><span>{p.n}</span><b>{p.v}</b></div>}
