'use client';
import {useEffect,useMemo,useState} from 'react';
type E=Record<string,any>;
const API=process.env.NEXT_PUBLIC_API_URL||'';
const NAV=[['overview','Overview'],['matrix','Liquidity Matrix'],['smart','Smart Money'],['tokens','Token Scanner'],['pools','Pool Scanner'],['wallets','Wallet Intelligence'],['signals','Signals'],['risk','Risk Engine'],['whales','Whale Flow'],['history','Historical']];
const ENGINES=['Liquidity Zones','EQH / EQL','Trend','Liquidity Sweep','Safe Stop','HTF Liquidity','Dynamic Trendlines','Supply / Demand + BOS','Weekend Gap','Liquidity Void / FVG','RSI Divergence'];
export default function Home(){const [events,setEvents]=useState<E[]>([]),[signals,setSignals]=useState<E[]>([]),[metrics,setMetrics]=useState<E>({}),[dexes,setDexes]=useState<E[]>([]);const [chain,setChain]=useState<'solana'|'bnb'>('solana'),[view,setView]=useState('overview'),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[status,setStatus]=useState('CONNECTING');
 useEffect(()=>{const base=API||window.location.origin;let ws:WebSocket|undefined;try{ws=new WebSocket(base.replace(/^http/,'ws')+'/ws');ws.onopen=()=>setStatus('LIVE');ws.onclose=()=>setStatus('OFFLINE');ws.onerror=()=>setStatus('ERROR');ws.onmessage=e=>{try{const x=JSON.parse(e.data);setEvents(v=>[x,...v.filter(y=>!(x.txHash&&y.txHash===x.txHash&&x.type===y.type))].slice(0,500));if(x.type==='chain_status'&&x.status==='LIVE')setStatus('LIVE')}catch{}}}catch{setStatus('ERROR')};const load=async()=>{try{const [m,d,s,ev]=await Promise.all([fetch(base+'/api/metrics',{cache:'no-store'}),fetch(base+'/api/dex',{cache:'no-store'}),fetch(base+'/api/signals',{cache:'no-store'}),fetch(base+'/api/events',{cache:'no-store'})]);setMetrics(await m.json());setDexes(await d.json());setSignals(await s.json());const rows=await ev.json();if(Array.isArray(rows))setEvents(rows)}catch{}};load();const t=setInterval(load,3000);return()=>{ws?.close();clearInterval(t)}},[]);
 const source=metrics.sources||{},counts=metrics.dexEvents||{};const visible=useMemo(()=>events.filter(e=>e.chain===chain&&(filter==='all'||e.type===filter)&&(!query||JSON.stringify(e).toLowerCase().includes(query.toLowerCase()))),[events,chain,filter,query]);const chainDex=dexes.filter(d=>d.chain===chain),trades=visible.filter(e=>e.type==='trade'),launches=visible.filter(e=>e.type==='token_create'||e.type==='migration');
 return <main><div className="noise"/><header className="topbar"><div className="brand"><div className="brandMark">HZ</div><div><b>HANZI</b><span>LIQUIDITY INTELLIGENCE</span></div></div><div className="topSearch"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search token, pool, wallet or transaction"/></div><div className="topActions"><button className={chain==='solana'?'chainBtn active':'chainBtn'} onClick={()=>setChain('solana')}>SOLANA</button><button className={chain==='bnb'?'chainBtn active':'chainBtn'} onClick={()=>setChain('bnb')}>BNB</button><span className={'status '+(status==='LIVE'?'on':'')}>● {status}</span></div></header>
 <div className="layout"><aside className="sidebar"><div className="sideLabel">TERMINAL</div>{NAV.map(([id,label])=><button key={id} className={view===id?'navActive':''} onClick={()=>setView(id)}><span className="navDot"/>{label}</button>)}<div className="sideSep"/><div className="sideLabel">DATA SOURCES</div><Source name="Solana RPC" value={source.solana||'WAITING'}/><Source name="PumpPortal" value={source.pumpportal||'WAITING'}/><Source name="BSC RPC" value={source.bnb||'WAITING'}/><div className="sideFooter"><b>REAL DATA ONLY</b><span>No demo / no synthetic fallback</span></div></aside>
 <section className="content"><div className="pageHead"><div><div className="crumb">HANZI / {chain.toUpperCase()} / {view.toUpperCase()}</div><h1>{title(view)}</h1><p>Observed blockchain events, decoded transaction fields and transparent read-only intelligence.</p></div><div className="headControls"><button>1m</button><button>5m</button><button className="selected">15m</button><button>1h</button><button>4h</button><button>1D</button></div></div>
 <section className="heroBanner"><div className="heroText"><span>ON-CHAIN INTELLIGENCE TERMINAL</span><h2>Every price dislocation = opportunity.</h2><p>Monitor DEX flow, liquidity changes, launches, migrations, wallet identities and transaction-level balance changes across Solana and BNB.</p><div className="heroTags"><i>24/7 MONITORING</i><i>11 MATRIX ENGINES</i><i>READ-ONLY</i></div></div><div className="heroFlow"><b>LIVE PIPELINE</b><span>RPC / WebSocket</span><em>→</em><span>Transaction Decoder</span><em>→</em><span>Liquidity / Flow</span><em>→</em><span>Intelligence</span></div></section>
 <div className="kpis"><Kpi label="OBSERVED EVENTS" value={metrics.eventCount??events.length} note="real normalized feed"/><Kpi label="TRADES" value={metrics.tradeEvents??trades.length} note="decoded trade logs"/><Kpi label="LIQUIDITY EVENTS" value={metrics.liquidityEvents??visible.filter(e=>e.type==='liquidity').length} note="mint / burn / sync"/><Kpi label="TOKEN / LAUNCH" value={metrics.tokenEvents??launches.length} note="launch + migration"/><Kpi label="TRANSACTIONS" value={visible.filter(e=>e.txHash).length} note="with transaction hash"/></div>
 {view==='overview'&&<Overview chain={chain} source={source} events={visible} dexes={chainDex} counts={counts} signals={signals} setView={setView}/>} {view==='matrix'&&<Matrix rows={visible} filter={filter} setFilter={setFilter}/>} {view==='smart'&&<Smart rows={visible} signals={signals}/>} {view==='tokens'&&<Token rows={visible}/>} {view==='pools'&&<Pools rows={visible} dexes={chainDex} counts={counts}/>} {view==='wallets'&&<Wallets rows={visible}/>} {view==='signals'&&<Signals rows={signals}/>} {view==='risk'&&<Risk rows={visible}/>} {view==='whales'&&<Whales rows={visible}/>} {view==='history'&&<Matrix rows={visible} filter={filter} setFilter={setFilter}/>}<div className="matrixFooter" style={{marginTop:12}}>Decoder status: {visible.some(e=>e.type==='transaction_detail')?'transaction details received':'waiting for transaction detail fields'} · Data policy: NO DATA → NO SIGNAL · No paid trade stream is enabled automatically.</div></section></div></main>}
function title(v:string){return NAV.find(x=>x[0]===v)?.[1]||'Overview'}
function Source({name,value}:{name:string,value:string}){return <div className="source"><span><i className={value==='LIVE'?'good':''}/> {name}</span><b className={value==='LIVE'?'good':''}>{value}</b></div>}
function Kpi({label,value,note}:{label:string,value:any,note:string}){return <div className="kpi"><small>{label}</small><strong>{value}</strong><span>{note}</span></div>}
function Panel({title:heading,sub,children,wide=false}:{title:string,sub?:string,children:any,wide?:boolean}){return <section className={'panel '+(wide?'wide':'')}><div className="panelHead"><div><b>{heading}</b>{sub&&<span>{sub}</span>}</div><span className="panelCode">REAL</span></div>{children}</section>}
function Empty({text='NO DATA — waiting for real blockchain events.'}:{text?:string}){return <div className="empty"><span>∅</span><b>{text}</b><small>No synthetic value is inserted. This panel populates when the source emits the required fields.</small></div>}
function Overview({chain,source,events,dexes,counts,signals,setView}:{chain:string,source:E,events:E[],dexes:E[],counts:E,signals:E[],setView:(x:string)=>void}){const trades=events.filter(e=>e.type==='trade'),liq=events.filter(e=>e.type==='liquidity'),wallets=events.filter(e=>e.owner||e.creator||e.provider||e.sender||e.to);return <><div className="twoCol"><Panel title="MARKET STRUCTURE" sub="Observed event map" wide><div className="structure"><div className="chartBox"><div className="empty"><span>⌁</span><b>{trades.length?'REAL TRADE EVENTS AVAILABLE':'NO PRICE SERIES AVAILABLE'}</b><small>{trades.length?'Use Matrix / Pools for decoded amounts, reserves and transaction fields.':'Price requires decoded token pair or quote fields; no synthetic chart is drawn.'}</small></div></div><div className="engineList">{ENGINES.map((e,i)=><div className="engine" key={e}><span>{String(i+1).padStart(2,'0')}</span><b>{e}</b><em>{events.length?'DATA':'WAITING'}</em></div>)}</div></div></Panel><Panel title="INTELLIGENCE SCORE" sub="No fabricated score"><div className="scoreCard"><div className="scoreRing"><strong>—</strong><span>NO SCORE</span></div><div><b>Confluence not yet complete</b><p>Scoring requires decoded price, liquidity, wallet history and risk fields. The terminal will not invent them.</p></div></div><div className="miniRows"><M label="Trade flow" value={trades.length?'OBSERVED':'WAITING'}/><M label="Liquidity" value={liq.length?'OBSERVED':'WAITING'}/><M label="Wallet data" value={wallets.length?'OBSERVED':'WAITING'}/><M label="Signals" value={signals.length?'OBSERVED':'NO SIGNAL'}/></div></Panel></div><div className="threeCol"><Panel title="VENUE FLOW" sub={chain.toUpperCase()}><div className="venueList">{dexes.map(d=><div className="venue" key={d.id}><span>{d.name}</span><b>{counts[d.id]||0}</b><small>events</small></div>)}</div></Panel><Panel title="SMART MONEY" sub="identity fields"><IdentityRows rows={wallets}/></Panel><Panel title="RISK WATCH" sub="observed evidence"><RiskRows rows={events}/></Panel></div><div className="twoCol"><Panel title="LIVE EVENT STREAM" sub={`${events.length} visible`}><EventTable rows={events.slice(0,12)}/><button className="moreBtn" onClick={()=>setView('matrix')}>OPEN FULL MATRIX →</button></Panel><Panel title="SOURCE HEALTH"><Source name="Solana RPC" value={source.solana||'WAITING'}/><Source name="PumpPortal" value={source.pumpportal||'WAITING'}/><Source name="BSC RPC" value={source.bnb||'WAITING'}/><div className="policy"><b>DATA POLICY</b><span>NO DATA → NO SIGNAL</span></div></Panel></div></>}
function Matrix({rows,filter,setFilter}:{rows:E[],filter:string,setFilter:(x:string)=>void}){const types=['all','trade','liquidity','transaction_detail','token_create','migration','wallet_transfer','log','block','chain_status'];return <><div className="filterBar">{types.map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x.replaceAll('_',' ').toUpperCase()}</button>)}</div><Panel title="LIVE LIQUIDITY MATRIX" sub="Normalized real events"><EventTable rows={rows} detailed/><div className="matrixFooter">Showing {rows.length} real events. No mock rows are inserted.</div></Panel></>}
function Smart({rows,signals}:{rows:E[],signals:E[]}){const wallets=rows.filter(e=>e.owner||e.provider||e.sender||e.creator||e.to||e.from);return <><div className="threeCol"><Panel title="WALLET ACTIVITY"><IdentityRows rows={wallets}/></Panel><Panel title="EARLY BUY DETECTOR"><div className="empty"><span>⌁</span><b>{rows.some(e=>e.initialBuy)?'INITIAL BUY DATA OBSERVED':'NO EARLY-BUY CLASSIFICATION'}</b><small>Classification needs repeated wallet history and position outcomes; no label is fabricated.</small></div></Panel><Panel title="WALLET QUALITY"><div className="empty"><span>∅</span><b>NO HISTORICAL PNL</b><small>Win rate and realized PnL require persisted wallet history.</small></div></Panel></div><Panel title="DERIVED SIGNALS" sub="Observed fields only"><EventTable rows={signals} detailed/></Panel></>}
function Token({rows}:{rows:E[]}){return <Panel title="TOKEN SCANNER" sub="Launch / migration / bonding curve"><EventTable rows={rows.filter(e=>e.type==='token_create'||e.type==='migration')} detailed/></Panel>}
function Pools({rows,dexes,counts}:{rows:E[],dexes:E[],counts:E}){const r=rows.filter(e=>e.type==='trade'||e.type==='liquidity'||e.pool);return <><div className="threeCol">{dexes.slice(0,3).map(d=><Kpi key={d.id} label={d.name} value={counts[d.id]||0} note="observed events"/>)}</div><Panel title="POOL + LIQUIDITY EVENTS" sub="reserves / amounts / pair address when emitted"><EventTable rows={r} detailed/></Panel></>}
function Wallets({rows}:{rows:E[]}){const r=rows.filter(e=>e.owner||e.provider||e.sender||e.creator||e.to||e.from||e.wallet);return <Panel title="WALLET INTELLIGENCE" sub="Identity evidence; labels are not fabricated"><IdentityRows rows={r}/><EventTable rows={r} detailed/></Panel>}
function Signals({rows}:{rows:E[]}){return <Panel title="SIGNAL CENTER" sub="read-only / observed event fields"><EventTable rows={rows} detailed/></Panel>}
function Risk({rows}:{rows:E[]}){const r=rows.filter(e=>e.err||e.success===false||e.type==='liquidity'||e.type==='wallet_transfer');return <><div className="threeCol"><Kpi label="CONTRACT / TX ERRORS" value={r.filter(e=>e.success===false||e.err).length} note="observed only"/><Kpi label="LIQUIDITY CHANGES" value={rows.filter(e=>e.type==='liquidity').length} note="mint / burn / sync"/><Kpi label="TRANSFER EVENTS" value={rows.filter(e=>e.type==='wallet_transfer').length} note="wallet flow"/></div><Panel title="RISK EVIDENCE"><RiskRows rows={r}/><EventTable rows={r} detailed/></Panel></>}
function Whales({rows}:{rows:E[]}){const r=rows.filter(e=>e.amountQuote||e.amount0In||e.amount1In||e.amount0Out||e.amount1Out||e.amount);return <Panel title="WHALE FLOW" sub="value fields observed, not USD-normalized unless supplied"><EventTable rows={r} detailed/></Panel>}
function M({label,value}:{label:string,value:any}){return <div className="miniRow"><span>{label}</span><b>{value}</b></div>}
function IdentityRows({rows}:{rows:E[]}){if(!rows.length)return <Empty text="NO WALLET IDENTITIES DECODED"/>;return <div className="venueList">{rows.slice(0,8).map((e,i)=><div className="venue" key={i}><span className="mono">{short(e.owner||e.provider||e.sender||e.creator||e.from||e.to)}</span><b>{e.type||'event'}</b><small>{e.chain||'—'}</small></div>)}</div>}
function RiskRows({rows}:{rows:E[]}){if(!rows.length)return <Empty text="NO RISK EVIDENCE"/>;return <div className="venueList">{rows.slice(0,8).map((e,i)=><div className="venue" key={i}><span>{e.type==='liquidity'?'LIQUIDITY':e.success===false?'TX ERROR':e.type==='wallet_transfer'?'TRANSFER':'OBSERVED'}</span><b>{e.eventName||'—'}</b><small>{e.chain||'—'}</small></div>)}</div>}
function EventTable({rows,detailed=false}:{rows:E[],detailed?:boolean}){if(!rows.length)return <Empty/>;return <div className="tableWrap"><table><thead><tr><th>TIME</th><th>TYPE</th><th>VENUE</th><th>CHAIN</th><th>IDENTIFIER</th>{detailed&&<th>DETAIL</th>}</tr></thead><tbody>{rows.map((e,i)=><tr key={`${e.ts||0}-${e.txHash||e.pool||e.token||i}`}><td>{e.ts?new Date(e.ts).toLocaleTimeString():'—'}</td><td><b>{String(e.type||'event').replaceAll('_',' ').toUpperCase()}</b></td><td>{e.dex||e.source||'—'}</td><td>{String(e.chain||'—').toUpperCase()}</td><td className="mono">{short(e.txHash||e.token||e.pool||e.owner||e.creator||e.address)}</td>{detailed&&<td>{detail(e)}</td>}</tr>)}</tbody></table></div>}
function detail(e:E){const p=[e.symbol||e.name,e.eventName,e.side,e.amountQuote&&`quote ${e.amountQuote}`,e.amount0In&&`0in ${e.amount0In}`,e.amount1In&&`1in ${e.amount1In}`,e.amount0Out&&`0out ${e.amount0Out}`,e.amount1Out&&`1out ${e.amount1Out}`,e.reserve0&&`r0 ${e.reserve0}`,e.reserve1&&`r1 ${e.reserve1}`,e.delta!==undefined&&`Δ ${e.delta}`,e.slot&&`slot ${e.slot}`,e.blockNumber&&`block ${e.blockNumber}`].filter(Boolean);return p.join(' · ')||'observed'}
function short(x:any){if(x===undefined||x===null||x==='')return '—';const s=String(x);return s.length>20?s.slice(0,9)+'…'+s.slice(-7):s}
